# Generated by Django 3.1 on 2020-08-04 22:40

from django.db import migrations
import csv
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'restaurantes.csv'

def load_csv(apps,schema_editor):
    Restaurants = apps.get_model('restaurants_app','Restaurants')
    data_file = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(data_file)) as csv_file:
        csv_reader = csv.DictReader(csv_file)

        for row in csv_reader:
            id = row["id"]            
            rating = row["rating"]
            name = row["name"]
            site = row["site"]
            email = row["email"]
            phone = row["phone"]
            street = row["street"]
            city = row["city"]
            state = row["state"]
            lat = row["lat"]
            lng = row["lng"]
            location = fromstr(f'POINT({lng} {lat})', srid=4326)
            Restaurants(id=id,rating=rating,name=name,site=site,email=email,
                phone=phone,street=street,city=city,state=state,location=location).save()

class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_csv)
    ]